version: "25.0.3"
services:  
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=c2VjcmV0'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
  java_api_person:
    image: 'micropersona'
    restart: always
    container_name: 'java_api_person'
    build: .
    environment:
      - DATABASE_URL = jdbc:postgresql://postgres:5432/mydatabase
      - DATABASE_USERNAME = 'myuser'
      - DATABASE_PASSWORD = 'c2VjcmV0'
    ports:
      - '9000:2000'
    depends_on:
      - postgres
    links:
      - postgres
  
    
