version: "25.0.3"
services:  
  postgresf:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=accounts_db'
      - 'POSTGRES_PASSWORD=c2VjcmV0'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5435:5432'
  java_api_finanacial:
    image: 'microfinancial'
    container_name: 'java_api_financial'
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresf:5432/accounts_db
      - DATABASE_USERNAME='myuser'
      - DATABASE_PASSWORD='c2VjcmV0'
    ports:
      - '2002:2001'
    depends_on:
      - postgresf
    links:
      - postgresf
  
    
